version: '3'

services:

  mongo-db:
    image: mongo:latest
    env_file: ./.env
    ports:
      - "$DB_PORT:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo-db:/data/db
    networks:
      - todo-app

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_INITDB_ROOT_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    networks:
      - todo-app

  app-backend:
    container_name: todo-node-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo-db
    env_file: ./.env
    ports:
      - "$PORT:8080"
    environment:
      - DB_HOST=mongo-db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_PORT
    stdin_open: true # To keep open the terminal after docker build the container
    tty: true
    networks:
      - todo-app

volumes:
  mongo-db: {}

networks:
  todo-app:
