version: '3'

services:

  mongo-db:
    image: mongo:latest
    env_file: ./.env
    ports:
      - "$DB_PORT:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo-db:/data/db

  app-backend:
    container_name: todo-node-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo-db
    env_file: ./.env
    ports:
      - "$PORT:8080"
    environment:
      - DB_HOST=mongo-db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_PORT
    stdin_open: true # To keep open the terminal after docker build the container
    tty: true

volumes:
  mongo-db: {}

networks:
  todo-app: